const card=(icon,title,body)=>`<article class="as-guide-card"><div class="as-guide-icon">${icon}</div><div><h3>${title}</h3>${body}</div></article>`;
const flow=(items)=>`<div class="as-guide-flow">${items.map((x,i)=>`${i?'<i>→</i>':''}<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>`;
export function visualBibleHTML(){
  return `<div class="as-guide-overlay" id="visualBible"><div class="as-guide-book">
    <header><div><b>📖 Audio Studio · Biblia visual</b><span>Composición y SFX organizados como herramientas de producción: estructura, workspace, inspector y preview.</span></div><button class="as-rec-close" id="guideClose">×</button></header>
    <nav class="as-guide-nav"><button data-guide-to="start">Inicio</button><button data-guide-to="layout">Interfaz</button><button data-guide-to="music">Composición</button><button data-guide-to="timeline">Timeline</button><button data-guide-to="import">Importar</button><button data-guide-to="voice">Voice → Notes</button><button data-guide-to="sf2">Instrumentos</button><button data-guide-to="generators">Generators</button><button data-guide-to="sfx">SFX Studio</button><button data-guide-to="shortcuts">Shortcuts</button></nav>
    <main class="as-guide-pages">
      <section id="guide-start"><h2>Primero: qué hace Audio Studio</h2>${flow([['1 · Estructura','elige track o etapa SFX'],['2 · Crea','graba, dibuja o genera'],['3 · Preview','escucha antes de confirmar'],['4 · Ajusta','Inspector contextual'],['5 · Exporta','WAV listo para el proyecto']])}
        <div class="as-guide-grid">${card('🎼','Composition Studio','<p>Arrangement, Piano Roll, Mixer, Voice Takes, SoundFonts y generadores dentro de un mismo flujo.</p>')}${card('✦','SFX Studio','<p>Construye un evento desde Tone/Noise/Sub/Transient, envelope, procesamiento y variantes de gameplay.</p>')}${card('🟢','Guided','<p>Expone decisiones musicales claras y mantiene la interfaz limpia.</p>')}${card('🔴','Studio / Pro','<p>Añade mezcla, capas, síntesis y parámetros finos sin cambiar de herramienta.</p>')}</div>
        <div class="as-guide-note"><b>Cry Designer está fuera de esta fase.</b> Primero se completa y estabiliza composición + creación de SFX.</div>
      </section>
      <section id="guide-layout"><h2>La lógica visual</h2>${flow([['Izquierda','estructura + recursos + acciones rápidas'],['Centro','trabajo y preview'],['Derecha','propiedades de la selección'],['Arriba','transport y contexto'],['Abajo','estado del motor']])}
        <div class="as-guide-grid">${card('☰','Estructura','<p>Como Layers/Sequence en los otros editores: seleccionas una pista o una etapa SFX y toda la interfaz sigue esa selección.</p>')}${card('▣','Workspace','<p>El centro no es un formulario. Es la canción, Piano Roll, Mixer, waveform o preview que estás manipulando.</p>')}${card('⚙','Inspector','<p>Solo muestra parámetros relevantes a lo seleccionado; no mezcla propiedades de objetos distintos.</p>')}${card('▶','Preview inmediata','<p>Los cambios visuales y sonoros se pueden comprobar en el mismo flujo sin exportar primero.</p>')}</div>
      </section>
      <section id="guide-music"><h2>Composition Studio</h2>${flow([['Track Structure','Melody / Harmony / Bass / Drums'],['Arrangement','estructura temporal'],['Piano Roll','edición de notas'],['Mixer','balance de pistas'],['Instrument Stack','timbres independientes'],['Master','salida final']])}
        <div class="as-guide-grid">${card('▦','Arrangement','<p>Trabaja la canción completa sin bajar por una página larga. Arrangement y el editor de pista viven dentro del workspace central.</p>')}${card('🎹','Piano Roll','<p>El teclado queda fijo a la izquierda. Smart crea, selecciona, mueve y redimensiona según dónde hagas click; la lane inferior controla velocity.</p>')}${card('▥','Mixer','<p>Cada track tiene Volume, Pan, Mute y Solo; después todos llegan al Master.</p>')}${card('Layers','Instrument Stack','<p>Cada track tiene sus propias capas. Melody no presta automáticamente su instrumento a Harmony/Bass/Drums.</p>')}</div>
      </section>
      <section id="guide-timeline"><h2>Navegar por la canción</h2>${flow([['Navigator','visión completa'],['Click / Drag','salta a cualquier segundo'],['Timeline','edición local'],['Fit','encaja toda la canción'],['Follow','sigue el playhead']])}
        <div class="as-guide-grid">${card('▱','Song Navigator','<p>La miniatura sobre el workspace representa toda la canción. Haz click o arrastra para moverte sin pelear con un scroll largo.</p>')}${card('☰ / ◫','Paneles plegables','<p>Oculta Structure o Inspector cuando necesites más ancho para la timeline o el Piano Roll.</p>')}${card('🖱','Timeline','<p>Rueda mueve horizontalmente, Ctrl+rueda hace zoom y botón central arrastra.</p>')}${card('±','Bar jumps','<p>−1 bar / +1 bar sirven para desplazamientos musicales predecibles.</p>')}${card('⌖','Viewport','<p>En Arrangement el Navigator dibuja qué zona de la canción estás viendo actualmente.</p>')}</div>
      </section>

      <section id="guide-import"><h2>Importar y usar referencias</h2>${flow([['MIDI / MusicXML','lee notas, ritmo y tempo'],['Track mapping','elige Melody / Harmony / Bass / Drums'],['Instrument Stack','conserva tus sonidos'],['Reference audio','escucha una canción en paralelo'],['Compose','edita encima sin incrustar la referencia']])}
        <div class="as-guide-grid">${card('⇩','MIDI','<p>Importa .mid o .midi. Audio Studio separa los tracks y propone un destino, pero tú decides dónde cae cada uno.</p>')}${card('𝄞','MusicXML','<p>Importa .musicxml o .xml sin comprimir para traer notas desde editores de partitura.</p>')}${card('♫','Reference audio','<p>WAV/MP3/OGG/FLAC/M4A puede sonar junto a tu proyecto para copiar ritmos o estudiar una referencia. No se exporta con la canción.</p>')}${card('🎹','Sonido independiente','<p>Importar una composición no reemplaza tus SoundFonts ni stacks: trae performance, no timbre.</p>')}</div>
      </section>
      <section id="guide-voice"><h2>Voice → Notes</h2>${flow([['Record','PCM musical'],['Analyze','pitch + continuidad'],['Select take','elige el tramo útil'],['Preview placed','escucha con la canción'],['Insert','confirma al final']])}
        <div class="as-guide-grid">${card('🎙','Destino','<p>La toma puede ir a Melody, Harmony o Bass y colocarse en un segundo exacto.</p>')}${card('🎧','Referencia','<p>Puedes escuchar canción/metrónomo mientras grabas. Auriculares siguen dando la señal más limpia.</p>')}${card('✂','Take range','<p>No tienes que convertir toda la grabación: elige solo la frase que necesitas.</p>')}${card('↕','Voice range','<p>Auto/Low/Mid/High restringe el tracker cuando insiste en octavas o tonos de fondo incorrectos.</p>')}</div>
      </section>
      <section id="guide-sf2"><h2>Instrumentos y SoundFonts</h2>${flow([['Track','elige propietario'],['Layer','elige capa'],['Bank','DPP/HGSS/BW/BW2/externo'],['Preset','busca por nombre'],['Audition','▶'],['Use','asigna solo a esa capa']])}
        <div class="as-guide-grid">${card('🎼','Biblioteca por nombre','<p>No necesitas trabajar con Bank/Program salvo que quieras ver el dato técnico.</p>')}${card('Layers','Capas independientes','<p>Piano + Strings + Bell pueden tocar la misma performance con volume, pan y transpose propios.</p>')}${card('🥁','Drums','<p>Drums tiene su propio Instrument Stack y nunca reutiliza automáticamente el de Melody.</p>')}${card('➕','External SF2','<p>Modern u otros bancos se pueden añadir durante la sesión sin inflar el paquete base.</p>')}</div>
      </section>
      <section id="guide-generators"><h2>Generadores</h2>${flow([['Configure','speed / velocity / density / style'],['Proposal','se crea temporalmente'],['Preview','escucha con o sin canción'],['Adjust','corrige parámetros'],['Apply','solo entonces modifica el arreglo']])}
        <div class="as-guide-note"><b>Importante:</b> Harmony/Bass/Drums generan contenido musical. No copian el timbre de Melody. El instrumento se decide independientemente en el Instrument Stack de cada track.</div>
      </section>
      <section id="guide-sfx"><h2>SFX Studio</h2>${flow([['Base','identidad inicial'],['Tone / Noise / Sub','cuerpo'],['Transient','ataque'],['Envelope','forma temporal'],['FX','Filter / Drive / Crush / Delay'],['Variants','pool de gameplay']])}
        <div class="as-guide-grid">${card('◆','Event','<p>Power, Pitch, Length y Texture controlan el carácter general. Úsalos primero.</p>')}${card('T/N/S','Layers','<p>Tone da cuerpo tonal, Noise textura y Sub peso. Cada etapa se puede desactivar.</p>')}${card('⚡','Transient','<p>Ataque ultracorto que ayuda a leer golpes, clicks, snaps y contactos sin simplemente subir volumen.</p>')}${card('⌁','Envelope','<p>Define cómo aparece y desaparece el sonido: Attack, Decay y Sustain. La curva se ve en el centro.</p>')}${card('F/D/C/↻','Processing','<p>Filter, Drive, Crush y Delay son etapas independientes con bypass propio.</p>')}${card('🎲','Variants','<p>Genera varias versiones controladas del mismo evento para evitar repetición mecánica durante gameplay.</p>')}</div>
        <div class="as-guide-note"><b>Lectura del SFX Stack:</b> selecciona una etapa a la izquierda → escucha el resultado en el centro → modifica solo esa etapa en el Inspector → compara de nuevo.</div>
      </section>
      <section id="guide-shortcuts"><h2>Shortcuts</h2><div class="as-shortcut-grid"><kbd>Space</kbd><span>Play / Stop</span><kbd>Ctrl + Z</kbd><span>Undo</span><kbd>Ctrl + Y</kbd><span>Redo</span><kbd>Ctrl + Shift + Z</kbd><span>Redo</span><kbd>Ctrl + wheel</kbd><span>Zoom timeline</span><kbd>Middle drag</kbd><span>Pan timeline / Piano Roll</span><kbd>1 / 2 / 3 / 4</kbd><span>Smart / Draw / Select / Erase</span><kbd>Delete</kbd><span>Delete selected note</span><kbd>Song Navigator drag</kbd><span>Scrub / jump</span></div></section>
    </main>
  </div></div>`;
}
