const STYLE_ID = "pokemon-icon-studio-styles";

export const css = `
#pis-root{--pis-bg:#11151b;--pis-panel:#171c24;--pis-panel2:#1d2430;--pis-line:#2b3544;--pis-text:#edf2f7;--pis-muted:#97a4b4;--pis-accent:#6fb1ff;--pis-good:#69d597;--pis-warn:#f1c96a;--pis-bad:#ff7c83;position:relative;width:100%;height:100%;min-height:620px;overflow:hidden;background:var(--pis-bg);color:var(--pis-text);font-family:Inter,"Segoe UI",Arial,sans-serif;font-size:13px;display:flex;flex-direction:column;letter-spacing:.01em}
#pis-root *{box-sizing:border-box}
#pis-root button,#pis-root input,#pis-root select{font:inherit}
.pis-top{height:58px;display:flex;align-items:center;gap:10px;padding:8px 12px;border-bottom:1px solid var(--pis-line);background:#141920;flex:0 0 auto}
.pis-brand{display:flex;align-items:center;gap:9px;min-width:270px}.pis-brand-mark{width:34px;height:34px;border:1px solid #3b4a5f;border-radius:9px;display:grid;place-items:center;font-size:20px;background:#202938}.pis-brand-title{font-size:16px;font-weight:760}.pis-brand-sub{font-size:11px;color:var(--pis-muted);margin-top:2px}
.pis-top-spacer{flex:1}.pis-status{max-width:420px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--pis-muted);font-size:12px}.pis-status[data-kind="ok"]{color:var(--pis-good)}.pis-status[data-kind="warn"]{color:var(--pis-warn)}.pis-status[data-kind="error"]{color:var(--pis-bad)}
.pis-btn{border:1px solid #344154;background:#202937;color:var(--pis-text);border-radius:7px;padding:7px 10px;cursor:pointer;transition:.12s ease;white-space:nowrap}.pis-btn:hover{background:#273446;border-color:#465a73}.pis-btn:disabled{opacity:.42;cursor:default}.pis-btn.primary{background:#2766a8;border-color:#347fcf}.pis-btn.primary:hover{background:#2e73bb}.pis-btn.good{background:#1d6947;border-color:#27875d}.pis-btn.danger{background:#5a2830;border-color:#7b3742}.pis-btn.icon{padding:7px 9px;min-width:34px}.pis-btn.small{padding:5px 7px;font-size:12px}.pis-btn.active{outline:2px solid #557aa7;background:#2a3850}
.pis-main{display:grid;grid-template-columns:minmax(235px,290px) minmax(420px,1fr) minmax(260px,330px);min-height:0;flex:1}.pis-left,.pis-right{background:var(--pis-panel);min-height:0;display:flex;flex-direction:column}.pis-left{border-right:1px solid var(--pis-line)}.pis-right{border-left:1px solid var(--pis-line)}.pis-center{min-height:0;display:flex;flex-direction:column;background:#10141a}
.pis-section-head{padding:10px 11px 8px;border-bottom:1px solid var(--pis-line);display:flex;align-items:center;gap:7px;flex:0 0 auto}.pis-section-title{font-weight:700}.pis-count{color:var(--pis-muted);font-size:11px;margin-left:auto}
.pis-search-wrap{padding:9px;border-bottom:1px solid var(--pis-line);display:flex;gap:6px}.pis-input,.pis-select{width:100%;background:#10151c;border:1px solid #323d4d;color:var(--pis-text);border-radius:6px;padding:7px 8px;outline:none}.pis-input:focus,.pis-select:focus{border-color:#4d82bd;box-shadow:0 0 0 1px #4d82bd55}.pis-input[type=number]{text-align:right}
.pis-filter-row{display:flex;gap:5px;padding:0 9px 8px;border-bottom:1px solid var(--pis-line)}
.pis-list{min-height:0;overflow:auto;padding:5px}.pis-row{height:52px;border:1px solid transparent;border-radius:7px;display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:8px;padding:4px 7px;cursor:pointer}.pis-row:hover{background:#1c2531}.pis-row.selected{background:#243245;border-color:#3b526d}.pis-row.missing .pis-thumb{border-style:dashed}.pis-thumb{width:38px;height:38px;border:1px solid #303c4c;border-radius:5px;background-color:#10151c;background-image:linear-gradient(45deg,#18202a 25%,transparent 25%),linear-gradient(-45deg,#18202a 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#18202a 75%),linear-gradient(-45deg,transparent 75%,#18202a 75%);background-size:10px 10px;background-position:0 0,0 5px,5px -5px,-5px 0;overflow:hidden;position:relative;display:grid;place-items:center;color:#617084;font-size:11px}.pis-thumb img{image-rendering:pixelated;position:absolute;left:0;top:0;max-width:none;max-height:none}.pis-row-name{font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pis-row-meta{color:var(--pis-muted);font-size:11px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pis-row-id{color:#7f8b9b;font:11px ui-monospace,SFMono-Regular,Consolas,monospace}
.pis-center-head{height:45px;border-bottom:1px solid var(--pis-line);display:flex;align-items:center;gap:6px;padding:6px 10px;background:#151a22}.pis-center-title{font-weight:700;margin-right:7px}.pis-tabs{display:flex;gap:4px}.pis-tab{min-width:70px}
.pis-stage-wrap{flex:1;min-height:260px;display:flex;align-items:center;justify-content:center;padding:20px;overflow:auto;position:relative}.pis-stage-card{display:flex;flex-direction:column;align-items:center;gap:10px}.pis-stage{position:relative;display:inline-block;border:1px solid #38485c;border-radius:8px;overflow:hidden;background-color:#0f141a;background-image:linear-gradient(45deg,#202a36 25%,transparent 25%),linear-gradient(-45deg,#202a36 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#202a36 75%),linear-gradient(-45deg,transparent 75%,#202a36 75%);background-size:20px 20px;background-position:0 0,0 10px,10px -10px,-10px 0;box-shadow:0 16px 50px #0008}.pis-stage canvas{display:block;image-rendering:pixelated;cursor:grab;touch-action:none}.pis-stage canvas:active{cursor:grabbing}.pis-stage-empty{width:min(520px,60vw);min-height:300px;border:1px dashed #354255;border-radius:10px;display:grid;place-items:center;text-align:center;color:var(--pis-muted);padding:30px}.pis-stage-empty strong{display:block;color:var(--pis-text);font-size:15px;margin-bottom:7px}
.pis-stage-info{color:var(--pis-muted);font-size:12px;text-align:center;max-width:660px}.pis-stage-info .bad{color:var(--pis-bad)}.pis-stage-info .warn{color:var(--pis-warn)}.pis-stage-info .good{color:var(--pis-good)}
.pis-toolbar{border-top:1px solid var(--pis-line);background:#151a22;padding:8px 10px;display:flex;gap:6px;align-items:center;flex-wrap:wrap;flex:0 0 auto}.pis-toolbar .sep{width:1px;height:25px;background:var(--pis-line);margin:0 2px}.pis-toolbar-label{color:var(--pis-muted);font-size:11px;margin-right:2px}
.pis-right-scroll{overflow:auto;min-height:0;padding-bottom:15px}.pis-inspector-block{padding:11px;border-bottom:1px solid var(--pis-line)}.pis-inspector-block h3{font-size:12px;margin:0 0 9px;color:#c8d2df;text-transform:uppercase;letter-spacing:.08em}.pis-kv{display:grid;grid-template-columns:82px 1fr;gap:7px 8px;align-items:center;margin-bottom:7px}.pis-kv label{color:var(--pis-muted);font-size:12px}.pis-mono{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;color:#b8c2cf;word-break:break-all;background:#111720;border:1px solid #293342;border-radius:5px;padding:7px}.pis-offset-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.pis-offset-cell label{display:block;color:var(--pis-muted);font-size:11px;margin-bottom:4px}.pis-btn-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.pis-check{display:flex;align-items:center;gap:7px;color:#c7d0dc;margin:7px 0}.pis-check input{accent-color:#5e9ce0}.pis-range{width:100%}.pis-diagnostic{border:1px solid #334052;background:#121821;border-radius:7px;padding:8px;color:var(--pis-muted);line-height:1.45}.pis-diagnostic.bad{border-color:#66363d;color:#ff9aa0}.pis-diagnostic.good{border-color:#2f5c49;color:#86dfaa}
.pis-toast-stack{position:absolute;right:14px;top:66px;display:flex;flex-direction:column;gap:7px;z-index:20;pointer-events:none}.pis-toast{max-width:420px;background:#212b39;border:1px solid #40516a;border-radius:8px;padding:9px 11px;box-shadow:0 10px 30px #0009;animation:pis-in .15s ease}.pis-toast.error{border-color:#7b3943;background:#3b2027}.pis-toast.ok{border-color:#2e6a4c;background:#19362a}@keyframes pis-in{from{opacity:0;transform:translateY(-5px)}to{opacity:1;transform:none}}
.pis-hidden{display:none!important}.pis-drop{outline:2px dashed #67a8ee;outline-offset:-8px}.pis-loading{opacity:.6;pointer-events:none}.pis-chip{display:inline-flex;align-items:center;border:1px solid #344155;background:#1b2430;color:#b9c5d2;border-radius:999px;padding:2px 6px;font-size:10px}.pis-chip.missing{color:#efc66d;border-color:#5b5033}.pis-unsaved{color:var(--pis-warn)}

.pis-filter-wrap{flex-wrap:wrap}.pis-filter-wrap .pis-btn:last-child{margin-left:auto}
.pis-row.pis-jump-flash{animation:pis-jump .7s ease}@keyframes pis-jump{0%,100%{box-shadow:none}35%{box-shadow:0 0 0 2px #75b6ff inset;background:#2b4160}}
.pis-color{width:100%;height:34px;padding:2px;background:#10151c;border:1px solid #323d4d;border-radius:6px}.pis-color:disabled{opacity:.45}
.pis-kv-stack{grid-template-columns:82px 1fr;margin-top:8px}
.pis-modal-overlay{position:absolute;inset:0;background:#000a;z-index:100;display:grid;place-items:center;padding:20px}.pis-modal{width:min(440px,92%);background:#1c2430;border:1px solid #405069;border-radius:10px;box-shadow:0 20px 60px #000b;padding:16px}.pis-modal-title{font-size:15px;font-weight:750;margin-bottom:8px}.pis-modal-text{color:#c6d0dc;line-height:1.5}.pis-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}
.pis-tool-row{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:8px}.pis-color-preview{width:22px;height:22px;border:1px solid #3a475a;border-radius:4px;display:inline-block;flex:0 0 22px}.pis-palette{display:flex;flex-wrap:wrap;gap:5px;min-height:22px;margin-top:6px;max-height:88px;overflow:auto;padding:4px;background:#10151c;border:1px solid #2b3544;border-radius:6px}.pis-swatch{width:22px;height:22px;border:1px solid #3d4a5e;border-radius:4px;cursor:pointer;flex:0 0 22px}.pis-swatch:hover{outline:2px solid #6fb1ff;outline-offset:1px}.pis-battler-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:6px}.pis-battler-thumb{width:64px;height:64px;border:1px solid #303c4c;border-radius:6px;background-color:#10151c;background-image:linear-gradient(45deg,#18202a 25%,transparent 25%),linear-gradient(-45deg,#18202a 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#18202a 75%),linear-gradient(-45deg,transparent 75%,#18202a 75%);background-size:10px 10px;background-position:0 0,0 5px,5px -5px,-5px 0;display:grid;place-items:center;overflow:hidden;position:relative;color:#617084;font-size:11px;cursor:pointer}.pis-battler-thumb img,.pis-battler-thumb canvas{image-rendering:pixelated}.pis-battler-thumb img{max-width:64px;max-height:64px}.pis-battler-canvas{image-rendering:pixelated;display:block}.pis-battler-info{margin-top:4px;opacity:.9}.pis-scale-presets{margin-top:4px}
#pis-root.pis-standalone{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;z-index:2147483000!important}
#pis-root.pis-fullscreen-active{position:fixed!important;inset:0!important;top:0!important;left:0!important;right:0!important;bottom:0!important;width:100vw!important;height:100vh!important;min-width:0!important;min-height:0!important;max-width:none!important;max-height:none!important;margin:0!important;border:0!important;border-radius:0!important;z-index:5000!important;box-shadow:none!important;background:var(--pis-bg,#11151b)!important}
@supports(height:100dvh){#pis-root.pis-fullscreen-active{height:100dvh!important}}
html.pis-fullscreen-lock,body.pis-fullscreen-lock{overflow:hidden!important;overscroll-behavior:none!important}
@media(max-width:1050px){.pis-main{grid-template-columns:240px minmax(380px,1fr)}.pis-right{position:absolute;right:0;top:58px;bottom:0;width:310px;z-index:5;box-shadow:-14px 0 30px #0008}.pis-right.collapsed{display:none}.pis-brand{min-width:200px}.pis-status{display:none}}
`;

export function installStyles() {
  let node = document.getElementById(STYLE_ID);
  if (node) return node;
  node = document.createElement("style");
  node.id = STYLE_ID;
  node.textContent = css;
  document.head.appendChild(node);
  return node;
}
