module MoveClasses
  KICK_MOVES = [
    :DOUBLEKICK, :JUMPKICK, :HIGHJUMPKICK, :MEGAKICK, :LOWKICK,
    :ROLLINGKICK, :TRIPLEKICK, :BLAZEKICK, :TROPKICK, :THUNDEROUSKICK,
    :AXEKICK, :LOWSWEEP, :STOMP, :HIGHHORSEPOWER, :STOMPINGTANTRUM,
    :CLOSECOMBAT, :BEDROCKKICK, :TRIPLEARROWS
  ].freeze

  PUNCH_MOVES = [
    :COMETPUNCH, :MEGAPUNCH, :FIREPUNCH, :ICEPUNCH, :THUNDERPUNCH,
    :DIZZYPUNCH, :MACHOPUNCH, :BULLETPUNCH, :POWERUPPUNCH,
    :DRAINPUNCH, :FOCUSPUNCH, :HAMMERARM, :SHADOWPUNCH, :SUCKERPUNCH,
    :SKYUPPERCUT, :PLASMAFISTS, :DOUBLEIRONBASH, :METEORMASH,
    :COLLISIONCOURSE, :HANDSPRINGS
  ].freeze
end
