const PANEL_ID = "dex-catalog-studio";
const PBS_PATH = "PBS/regional_dexes.txt";
const CONFIG_PATH = "Data/SpeciesDex/config.json";
const ICON_LIST = `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 6h2M10 6h9M5 12h2M10 12h9M5 18h2M10 18h9" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>`;
const ICON_FULLSCREEN = `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/></svg>`;
const iconPath = (value) => {
  const parts = String(value || "").split(",");
  const species = upper(parts[0]);
  const form = Number(parts[1] || 0);
  const suffix = form > 0 ? `_${form}` : "";
  return [`Graphics/Pokemon/Icons/${species}${suffix}.png`, `Graphics/Pokemon/Icons/${species}.png`];
};

const esc = (value) => String(value ?? "").replace(/[&<>\"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const upper = (value) => String(value ?? "").trim().toUpperCase();
const key = (id, form = 0) => form ? `${upper(id)},${Number(form)}` : upper(id);
const pbsSpeciesId = (value) => {
  const raw = upper(value);
  const match = raw.match(/^(.+?)_(\d+)$/);
  return match ? key(match[1], Number(match[2])) : raw;
};
const pbsExportId = (value) => {
  const raw = upper(value);
  const match = raw.match(/^(.+?),(\d+)$/);
  return match ? `${match[1]}_${match[2]}` : raw;
};
const parsePbs = (text) => {
  const dexes = [];
  let current = null;
  for (const raw of String(text || "").replace(/\r/g, "").split("\n")) {
    const line = raw.trim();
    const header = line.match(/^\[(\d+)\]$/);
    if (header) { current = { id: Number(header[1]), species: [] }; dexes[current.id] = current; continue; }
    if (!current || !line || line.startsWith("#")) continue;
    line.split(",").map(pbsSpeciesId).filter(Boolean).forEach((id) => { if (!current.species.includes(id)) current.species.push(id); });
  }
  return dexes.filter(Boolean);
};
const writePbs = (dexes) => {
  const out = ["# Generated by Dex Catalog Studio.", "# Edit with the Studio to preserve ordering and enabled-dex metadata.", ""];
  dexes.forEach((dex, index) => {
    out.push("#-------------------------------", `[${index}]`);
    for (let i = 0; i < dex.species.length; i += 20) out.push(dex.species.slice(i, i + 20).map(pbsExportId).join(","));
    out.push("");
  });
  return out.join("\n");
};
const css = `
.dcs{height:100%;min-height:620px;background:#121820;color:#e8edf2;display:grid;grid-template-rows:64px minmax(0,1fr);font:12px/1.35 ui-monospace,SFMono-Regular,Consolas,monospace}.dcs *{box-sizing:border-box}.dcs button,.dcs input,.dcs select{font:inherit}.dcs-top{display:flex;align-items:center;gap:9px;padding:10px 13px;border-bottom:1px solid #2d3a47;background:#1c2731}.dcs-title{font-size:16px;font-weight:800}.dcs-sub{font-size:9px;color:#8fa0ad}.dcs-icon{width:24px;height:24px;color:#83c9c1}.dcs-icon svg{width:100%;height:100%}.dcs-mon-icon{width:26px;height:26px;object-fit:contain;image-rendering:pixelated;display:block}.dcs-mon-icon.fallback{border:2px solid #65bcb3;border-radius:50%;position:relative}.dcs-mon-icon.fallback:after{content:"";position:absolute;left:2px;right:2px;top:10px;border-top:2px solid #65bcb3}.dcs-sp{flex:1}.dcs-btn{border:1px solid #405160;border-radius:6px;background:#202d38;color:inherit;padding:7px 10px;cursor:pointer}.dcs-btn:hover,.dcs-btn.active{border-color:#76c7bd;background:#263e43}.dcs-btn.primary{background:#277e78;border-color:#55bdb2;color:white}.dcs-btn.icon{width:34px;padding:0}.dcs-btn.icon svg{width:16px;height:16px}.dcs-main{display:grid;grid-template-columns:270px 1fr 300px;min-height:0}.dcs-side,.dcs-center,.dcs-right{min-height:0;overflow:auto}.dcs-side{border-right:1px solid #2d3a47;padding:11px;background:#17212a}.dcs-center{padding:12px}.dcs-right{border-left:1px solid #2d3a47;padding:11px;background:#17212a}.dcs-field{display:grid;gap:5px;margin-bottom:10px}.dcs-field label{font-size:9px;color:#9db0bd;text-transform:uppercase}.dcs-input,.dcs-select{width:100%;padding:7px 8px;background:#10161c;color:inherit;border:1px solid #3b4b58;border-radius:5px}.dcs-dex{display:flex;align-items:center;justify-content:space-between;padding:8px;border:1px solid transparent;border-radius:6px;cursor:pointer}.dcs-dex:hover,.dcs-dex.on{background:#22343c;border-color:#477b7d}.dcs-dex small{color:#93a6b2}.dcs-card{border:1px solid #2d3a47;border-radius:8px;background:#18232c;padding:11px;margin-bottom:11px}.dcs-card h3{font-size:11px;margin:0 0 9px;color:#abd0cb}.dcs-check{display:flex;align-items:center;gap:7px;margin:8px 0;color:#cad5da}.dcs-check input{width:16px;height:16px}.dcs-list{display:grid;gap:4px;max-height:calc(100vh - 225px);overflow:auto}.dcs-row{display:grid;grid-template-columns:24px 26px 38px minmax(0,1fr) auto;align-items:center;gap:8px;padding:7px 8px;border:1px solid #2e3b46;border-radius:5px;background:#17212a;cursor:pointer}.dcs-row:hover,.dcs-row.on{border-color:#58aaa3;background:#20353a}.dcs-num{color:#83c9c1;text-align:right}.dcs-row small{display:block;color:#899ba7;font-size:9px}.dcs-actions{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:9px}.dcs-muted{color:#91a0ab;font-size:10px}.dcs-warning{border-left:3px solid #e1a65e;padding:8px;background:#2c271e;color:#e8c18d;font-size:10px}.dcs.dcs-fullscreen-active{position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;min-height:0!important;z-index:2147482000!important}.dcs-fullscreen-lock{overflow:hidden!important;overscroll-behavior:none!important}
.dcs-frow{display:flex;align-items:center;gap:8px;padding:3px 8px 3px 46px;border-bottom:1px solid #263542;background:#141d26;font-size:11px}.dcs-frow .dcs-check{display:inline-flex;align-items:center;gap:4px;margin:0;color:#b9c8d3;text-transform:none}.dcs-fnum{color:#76c7bd;font-weight:700;width:26px}.dcs-fbadge{margin-left:auto;background:#1f4a45;border:1px solid #57b3a8;color:#9fe2d8;border-radius:9px;padding:1px 7px;font-size:10px;font-weight:700}@media(max-width:1050px){.dcs-main{grid-template-columns:220px minmax(0,1fr)}.dcs-right{display:none}}
`;

export function activate(ctx) {
  ctx.ui.registerPanel({ id:PANEL_ID, title:"Dex Catalog Studio", icon:"list", defaultPosition:"right", defaultSize:{width:1280,height:850}, showInMenu:false, render:(host)=>render(ctx, host) });
  ctx.menu.registerMenuItem({ menu:"Mods", label:"Dex Catalog Studio", icon:"list", handler:()=>ctx.ui.openPanel(PANEL_ID) });
  ctx.commands.register("dex-catalog-studio.open", ()=>ctx.ui.openPanel(PANEL_ID));
}

async function render(ctx, host) {
  host.innerHTML = `<style>${css}</style><div class="dcs"><header class="dcs-top"><span class="dcs-icon">${ICON_LIST}</span><div><div class="dcs-title">Dex Catalog Studio</div><div class="dcs-sub">Orden, Pokédex habilitadas y disponibilidad Nacional</div></div><div class="dcs-sp"></div><button class="dcs-btn icon" data-full title="Pantalla completa · F11"><span data-full-icon>${ICON_FULLSCREEN}</span></button><button class="dcs-btn" data-reload>Recargar</button><button class="dcs-btn primary" data-save>Guardar JSON + PBS</button></header><main class="dcs-main"><aside class="dcs-side"><div class="dcs-card"><h3>Pokédex del juego</h3><div data-dexes></div><button class="dcs-btn" data-add style="width:100%;margin-top:8px">+ Añadir Pokédex</button></div><div class="dcs-card"><h3>Biblioteca PBS</h3><input class="dcs-input" data-pool-search placeholder="Buscar especie para añadir..."><label class="dcs-check"><input type="checkbox" data-show-forms> Mostrar formas PBS</label><div class="dcs-actions"><button class="dcs-btn" data-select-all>Seleccionar visibles</button><button class="dcs-btn" data-clear-selection>Limpiar selección</button></div><div class="dcs-list" data-pool></div></div></aside><section class="dcs-center"><div class="dcs-card"><h3 data-heading>Especies de la Dex</h3><input class="dcs-input" data-dex-search placeholder="Buscar dentro de esta Dex..." style="margin-bottom:9px"><div class="dcs-actions"><button class="dcs-btn" data-up>Subir seleccionadas</button><button class="dcs-btn" data-down>Bajar seleccionadas</button><button class="dcs-btn" data-add-selected>Añadir selección</button><button class="dcs-btn" data-remove>Quitar selección</button></div><div class="dcs-list" data-list></div></div></section><aside class="dcs-right"><div class="dcs-card"><h3>Estado ingame</h3><label class="dcs-check"><input type="checkbox" data-enabled checked> Dex seleccionada habilitada</label><label class="dcs-check"><input type="checkbox" data-national> Pokédex Nacional disponible</label><p class="dcs-muted">Una Dex deshabilitada queda vacía ingame y no alimenta ChangeDex ni la Libreta. El estado se guarda en JSON.</p></div><div class="dcs-card"><h3>Configuración de la Dex Seleccionada</h3><div class="dcs-field"><label>Nombre de esta Pokédex</label><input class="dcs-input" data-dex-name placeholder="ej. Pokédex Payu"></div><div class="dcs-field"><label>Región (mapregion 0,1,2... vacío = región actual)</label><input class="dcs-input" data-dex-region placeholder="ej. 0"></div></div><div class="dcs-card"><h3>Pokédex Nacional</h3><div class="dcs-field"><label>Nombre</label><input class="dcs-input" data-national-name placeholder="Pokédex Nacional"></div></div></aside></main></div>`;
  const state = { dexes:[], selectedDex:0, selectedSpecies:null, selectedPool:new Set(), selectedEntries:new Set(), allSpecies:[], config:{schema:1,nationalAvailable:false,enabledDexes:[], dexNames:[], dexRegions:[], nationalDexName:"", forms:[]}, showForms:true, fullscreen:false, fullscreenPlaceholder:null };
  const read = async (path, fallback="") => { try { return await ctx.fs.readProjectFile(path); } catch (_) { return fallback; } };
  const readJson = async (path, fallback) => { try { const x=JSON.parse(await read(path)); return x && typeof x === "object" ? x : fallback; } catch (_) { return fallback; } };
  const write = async (path, value) => ctx.fs.writeProjectFile(path, value);
  const scanSpecies = async () => {
    let files=[];
    try { files=(await ctx.fs.listProjectDir("PBS")).map((x)=>String(x)).filter((x)=>/^pokemon.*\.txt$/i.test(x.split(/[\\/]/).pop() || "")); } catch (_) {}
    if (!files.length) files=["pokemon.txt"];
    const ids=[]; const seen=new Set();
    for (const file of files) {
      const text=await read(`PBS/${file.replace(/^PBS[\\/]/i,"")}`, "");
      for (const raw of text.replace(/\r/g,"").split("\n")) {
        const line=raw.trim(); const h=line.match(/^\[([^\]]+)\]/); if(!h)continue;
        const parts=h[1].split(",").map((x)=>x.trim()); const id=key(parts[0],parts[1] ? Number(parts[1]) : 0);
        if(id&&!seen.has(id)){seen.add(id);ids.push(id);}
      }
    }
    return ids;
  };
  const load = async () => { state.config=await readJson(CONFIG_PATH,{schema:1,nationalAvailable:false,enabledDexes:[],dexNames:[],dexRegions:[],nationalDexName:""}); const storedDexes=Array.isArray(state.config.dexes)&&state.config.dexes.every((list)=>Array.isArray(list)); state.dexes=storedDexes?state.config.dexes.map((species,id)=>({id,species:[...new Set(species.map(upper).filter(Boolean))]})):parsePbs(await read(PBS_PATH,"")); state.allSpecies=await scanSpecies(); state.config.enabledDexes=Array.isArray(state.config.enabledDexes)?state.config.enabledDexes:state.dexes.map((_,i)=>i); state.config.dexNames=Array.isArray(state.config.dexNames)?state.config.dexNames:[]; state.config.dexRegions=Array.isArray(state.config.dexRegions)?state.config.dexRegions:[]; state.config.nationalDexName=state.config.nationalDexName||""; state.config.forms=Array.isArray(state.config.forms)?state.config.forms:[]; if(!state.dexes.length)state.dexes=[{id:0,species:[]}]; state.selectedDex=Math.min(state.selectedDex,state.dexes.length-1); state.selectedEntries.clear();state.selectedPool.clear();renderAll(); };
  const dexesEl=host.querySelector("[data-dexes]"), listEl=host.querySelector("[data-list]"), poolEl=host.querySelector("[data-pool]"), heading=host.querySelector("[data-heading]"), poolSearch=host.querySelector("[data-pool-search]"), dexSearch=host.querySelector("[data-dex-search]"), enabled=host.querySelector("[data-enabled]"), national=host.querySelector("[data-national]"), showForms=host.querySelector("[data-show-forms]"), dexNameEl=host.querySelector("[data-dex-name]"), dexRegionEl=host.querySelector("[data-dex-region]"), nationalNameEl=host.querySelector("[data-national-name]");
  const root=host.querySelector(".dcs"), full=host.querySelector("[data-full]");
  showForms.checked=state.showForms;
  const iconUrlCache=new Map();
  const iconCache=new Map();
  const selected=()=>state.dexes[state.selectedDex] || {species:[]};
  async function projectUrl(path){
    if(iconUrlCache.has(path))return iconUrlCache.get(path);
    for(const owner of [ctx.fs,ctx.editor,ctx]){
      for(const name of ["projectFileUrl","assetUrl"]){
        if(typeof owner?.[name]!=="function")continue;
        try{const value=await owner[name](path);if(value){const result=String(value);iconUrlCache.set(path,result);return result;}}catch(_){ }
      }
    }
    const rootPath=String(ctx.editor?.gameRoot?.()||ctx.gameRoot?.()||"").replace(/[\\/]+$/g,"");
    const invoke=window.__TAURI__?.core?.invoke;
    if(rootPath&&typeof invoke==="function"){
      try{const bytes=await invoke("read_binary_file",{path:`${rootPath}/${path}`});if(bytes?.length){const arr=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);const result=URL.createObjectURL(new Blob([arr],{type:"image/png"}));iconUrlCache.set(path,result);return result;}}catch(_){ }
    }
    return null;
  }
  async function cropIcon(url){
    if(iconCache.has(url))return iconCache.get(url);
    return new Promise((resolve)=>{
      const image=new Image(); image.onload=()=>{try{
        const canvas=document.createElement("canvas"),context=canvas.getContext("2d");
        const frameWidth=image.naturalWidth>=image.naturalHeight*1.5?Math.floor(image.naturalWidth/2):image.naturalWidth;
        canvas.width=frameWidth;canvas.height=image.naturalHeight;context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,frameWidth,image.naturalHeight,0,0,frameWidth,image.naturalHeight);
        const data=context.getImageData(0,0,canvas.width,canvas.height).data;let minX=canvas.width,minY=canvas.height,maxX=-1,maxY=-1;
        for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){if(data[(y*canvas.width+x)*4+3]>8){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}}
        if(maxX<0){iconCache.set(url,url);resolve(url);return;} const pad=Math.max(2,Math.round(Math.max(maxX-minX+1,maxY-minY+1)*.06));minX=Math.max(0,minX-pad);minY=Math.max(0,minY-pad);maxX=Math.min(canvas.width-1,maxX+pad);maxY=Math.min(canvas.height-1,maxY+pad);
        const out=document.createElement("canvas");out.width=maxX-minX+1;out.height=maxY-minY+1;out.getContext("2d").drawImage(canvas,minX,minY,out.width,out.height,0,0,out.width,out.height);const result=out.toDataURL("image/png");iconCache.set(url,result);resolve(result);
      }catch(_){iconCache.set(url,url);resolve(url);}};image.onerror=()=>resolve(null);image.src=url;
    });
  }
  async function hydrateIcons(){
    const nodes=[...host.querySelectorAll("[data-icon-id]")];
    await Promise.all(nodes.map(async(node)=>{const paths=iconPath(node.dataset.iconId);let url=null;for(const path of paths){url=await projectUrl(path);if(url)break;}if(!url){node.classList.add("fallback");return;}const cropped=await cropIcon(url);if(cropped)node.src=cropped;}));
  }
  function updateFullscreenButton(){full.classList.toggle("active",state.fullscreen);full.title=state.fullscreen?"Salir de pantalla completa · F11 / Esc":"Pantalla completa · F11";}
  function setFullscreen(on){
    if(on===state.fullscreen)return;
    if(on){
      state.fullscreenPlaceholder=document.createComment("dcs-fullscreen");
      if(root.parentNode)root.parentNode.insertBefore(state.fullscreenPlaceholder,root);
      document.body.appendChild(root);
      root.classList.add("dcs-fullscreen-active");
      document.body.classList.add("dcs-fullscreen-lock");
      document.documentElement.classList.add("dcs-fullscreen-lock");
      state.fullscreen=true;
    }else{
      root.classList.remove("dcs-fullscreen-active");
      document.body.classList.remove("dcs-fullscreen-lock");
      document.documentElement.classList.remove("dcs-fullscreen-lock");
      if(state.fullscreenPlaceholder?.parentNode)state.fullscreenPlaceholder.parentNode.replaceChild(root,state.fullscreenPlaceholder);
      state.fullscreenPlaceholder=null;
      state.fullscreen=false;
    }
    updateFullscreenButton();
  }
  function renderAll(){
    dexesEl.innerHTML=state.dexes.map((d,i)=>`<div class="dcs-dex ${i===state.selectedDex?'on':''}" data-dex="${i}"><span>Dex ${i+1}</span><small>${state.config.enabledDexes.includes(i)?"HABILITADA":"DESHABILITADA"} · ${d.species.length}</small></div>`).join("");
    heading.textContent=`Dex ${state.selectedDex+1} · ${selected().species.length} especies`;
    enabled.checked=state.config.enabledDexes.includes(state.selectedDex); national.checked=!!state.config.nationalAvailable;
    // Per-dex name/region
    while(state.config.dexNames.length<=state.selectedDex)state.config.dexNames.push("");
    while(state.config.dexRegions.length<=state.selectedDex)state.config.dexRegions.push("");
    dexNameEl.value=state.config.dexNames[state.selectedDex]||"";
    dexRegionEl.value=state.config.dexRegions[state.selectedDex]!=null?state.config.dexRegions[state.selectedDex]:"";
    nationalNameEl.value=state.config.nationalDexName||"";
    const dexQ=upper(dexSearch.value), poolQ=upper(poolSearch.value); const rows=selected().species.map((id,i)=>({id,i})).filter(x=>!dexQ||x.id.includes(dexQ));
    const formRow=(base)=>{
      const baseKey=upper(base);
      const baseHidden=(state.config.forms||[]).some((h)=>upper(h)===baseKey);
      return state.allSpecies.filter((fid)=>!state.showForms?false:fid.startsWith(upper(base)+",")).map((fid)=>{
        const inSlot=selected().species.some((s)=>upper(s)===upper(fid));
        const hidden=(state.config.forms||[]).some((h)=>upper(h)===upper(fid));
        const fnum=upper(fid).split(",")[1];
        const slotNo=inSlot?selected().species.findIndex((s)=>upper(s)===upper(fid))+1:null;
        const badge=slotNo?`<span class="dcs-fbadge" title="Slot propio Nº ${slotNo} en la Pokédex">Nº ${slotNo}</span>`:"";
        return `<div class="dcs-frow"><span class="dcs-fnum">F${fnum}</span><label class="dcs-check" title="Forma en su propio slot del catálogo"><input type="checkbox" data-fslot="${esc(fid)}" ${inSlot?"checked":""}> Slot</label><label class="dcs-check" title="Mostrar en la página de formas"><input type="checkbox" data-fshow="${esc(fid)}" ${hidden?"":"checked"}> Ver</label>${badge}</div>`;
      });
    };
    listEl.innerHTML=rows.map(x=>{const formBlock=(!x.id.includes(",")&&state.showForms)?formRow(x.id):"";return `<label class="dcs-row ${state.selectedEntries.has(x.id)?'on':''}"><input type="checkbox" data-entry="${esc(x.id)}" ${state.selectedEntries.has(x.id)?"checked":""}><img class="dcs-mon-icon" data-icon-id="${esc(x.id)}" alt=""><span class="dcs-num">${x.i+1}</span><span><b>${esc(x.id)}</b><small>Entrada de la Pokédex</small></span><span>›</span></label>${formBlock}`;}).join("")||`<div class="dcs-muted">No hay especies en esta Pokédex.</div>`;
    const pool=state.allSpecies.filter((id)=>state.showForms||!id.includes(",")).filter((id)=>!poolQ||id.includes(poolQ));
    poolEl.innerHTML=pool.map((id)=>`<label class="dcs-row ${state.selectedPool.has(id)?'on':''}"><input type="checkbox" data-pool-id="${esc(id)}" ${state.selectedPool.has(id)?"checked":""}><img class="dcs-mon-icon" data-icon-id="${esc(id)}" alt=""><span class="dcs-num">+</span><span><b>${esc(id)}</b><small>Disponible en PBS</small></span><span>›</span></label>`).join("")||`<div class="dcs-muted">No hay coincidencias en los PBS pokemon*.txt.</div>`;
    hydrateIcons();
  }
  dexesEl.addEventListener("click",(e)=>{const el=e.target.closest("[data-dex]");if(!el)return;state.selectedDex=Number(el.dataset.dex);state.selectedSpecies=null;state.selectedEntries.clear();state.selectedPool.clear();renderAll();});
  listEl.addEventListener("change",(e)=>{
  const slot=e.target.dataset.fslot;
  if(slot){const d=selected(),k=upper(slot);const baseKey=k.split(",")[0];const baseHidden=(state.config.forms||[]).some((h)=>upper(h)===baseKey);state.config.forms=Array.isArray(state.config.forms)?state.config.forms:[];if(e.target.checked){if(!d.species.some((s)=>upper(s)===k))d.species.push(k);state.config.forms=state.config.forms.filter((h)=>upper(h)!==k);}else{d.species=d.species.filter((s)=>upper(s)!==k);if(baseHidden&&!state.config.forms.some((h)=>upper(h)===k))state.config.forms.push(k);}renderAll();return;}
  const show=e.target.dataset.fshow;
  if(show){const k=upper(show);state.config.forms=Array.isArray(state.config.forms)?state.config.forms:[];if(e.target.checked){state.config.forms=state.config.forms.filter((h)=>upper(h)!==k);}else if(!state.config.forms.some((h)=>upper(h)===k)){state.config.forms.push(k);}renderAll();return;}
  const id=e.target.dataset.entry;if(!id)return;e.target.checked?state.selectedEntries.add(id):state.selectedEntries.delete(id);renderAll();});
  poolEl.addEventListener("change",(e)=>{const id=e.target.dataset.poolId;if(!id)return;e.target.checked?state.selectedPool.add(id):state.selectedPool.delete(id);renderAll();});
  poolSearch.addEventListener("input",renderAll); dexSearch.addEventListener("input",renderAll); showForms.addEventListener("change",()=>{state.showForms=showForms.checked;renderAll();});
  dexNameEl.addEventListener("input",()=>{state.config.dexNames[state.selectedDex]=dexNameEl.value.trim();});
  dexRegionEl.addEventListener("input",()=>{const v=dexRegionEl.value.trim();state.config.dexRegions[state.selectedDex]=v===""||isNaN(v)?null:Number(v);});
  nationalNameEl.addEventListener("input",()=>{state.config.nationalDexName=nationalNameEl.value.trim();});
  host.querySelector("[data-up]").onclick=()=>move(-1); host.querySelector("[data-down]").onclick=()=>move(1);
  function move(delta){const d=selected(),chosen=d.species.filter((id)=>state.selectedEntries.has(id));if(!chosen.length)return;const indexes=chosen.map((id)=>d.species.indexOf(id)).sort((a,b)=>a-b);if(delta<0&&indexes[0]===0)return;if(delta>0&&indexes[indexes.length-1]===d.species.length-1)return;const set=new Set(chosen);const ordered=d.species.slice();if(delta<0){for(let i=1;i<ordered.length;i++)if(set.has(ordered[i])&&!set.has(ordered[i-1])){[ordered[i-1],ordered[i]]=[ordered[i],ordered[i-1]];}}else{for(let i=ordered.length-2;i>=0;i--)if(set.has(ordered[i])&&!set.has(ordered[i+1])){[ordered[i],ordered[i+1]]=[ordered[i+1],ordered[i]];}}d.species=ordered;renderAll();}
  host.querySelector("[data-remove]").onclick=()=>{const d=selected();d.species=d.species.filter((id)=>!state.selectedEntries.has(id));state.selectedEntries.clear();renderAll();};
  host.querySelector("[data-add-selected]").onclick=()=>{const d=selected();for(const id of state.selectedPool)if(!d.species.includes(id))d.species.push(id);state.selectedPool.clear();renderAll();};
  host.querySelector("[data-select-all]").onclick=()=>{const q=upper(poolSearch.value);state.allSpecies.filter((id)=>state.showForms||!id.includes(",")).filter((id)=>!q||id.includes(q)).forEach((id)=>state.selectedPool.add(id));renderAll();};
  host.querySelector("[data-clear-selection]").onclick=()=>{state.selectedPool.clear();state.selectedEntries.clear();renderAll();};
  host.querySelector("[data-add]").onclick=()=>{state.dexes.push({id:state.dexes.length,species:[]});state.selectedDex=state.dexes.length-1;state.config.enabledDexes.push(state.selectedDex);while(state.config.dexNames.length<state.dexes.length)state.config.dexNames.push("");while(state.config.dexRegions.length<state.dexes.length)state.config.dexRegions.push("");renderAll();};
  enabled.addEventListener("change",()=>{const s=new Set(state.config.enabledDexes);enabled.checked?s.add(state.selectedDex):s.delete(state.selectedDex);state.config.enabledDexes=[...s].sort((a,b)=>a-b);});
  national.addEventListener("change",()=>{state.config.nationalAvailable=national.checked;});
  full.onclick=()=>setFullscreen(!state.fullscreen);
  document.addEventListener("keydown",(event)=>{
    if(event.key==="F11"){event.preventDefault();setFullscreen(!state.fullscreen);}
    else if(event.key==="Escape"&&state.fullscreen){event.preventDefault();setFullscreen(false);}
  });
  host.querySelector("[data-reload]").onclick=load;
  host.querySelector("[data-save]").onclick=async()=>{try{if(typeof ctx.fs.projectMkdir!=="function")throw new Error("Maker Studio no expone projectMkdir");await ctx.fs.projectMkdir("Data");await ctx.fs.projectMkdir("Data/SpeciesDex");state.config.schema=1;state.config.dexes=state.dexes.map((dex)=>[...new Set(dex.species.map(upper).filter(Boolean))]);state.config.enabledDexes=state.config.enabledDexes.filter((i)=>i>=0&&i<state.dexes.length);const json=JSON.stringify(state.config,null,2)+"\n";await write(CONFIG_PATH,json);const saved=await read(CONFIG_PATH,"");if(saved.trim()!==json.trim())throw new Error("El JSON no pudo verificarse después de escribirlo");await write(PBS_PATH,writePbs(state.dexes));ctx.ui.showToast?.({message:"Catálogo guardado en JSON y exportado al PBS.",level:"success"});}catch(error){ctx.ui.showToast?.({message:`No se pudo guardar el catálogo: ${error.message||error}`,level:"error"});}};
  updateFullscreenButton();
  await load();
}
